### ISSUE TITLE
Retrying failed jobs not working

### ISSUE THREAD

**Issue by ericgaonz** [kainxspirits/laravel-pubsub-queue#15]
After a job has failed, I run the following:
`php artisan queue:retry all`

Which results in the following error message in the queue logs:
```
[2019-04-02 22:02:49][] Processing: 
[2019-04-02 22:02:49][] Failed:    
```

After further inspection, it would seem we are using `base64_encode()` too soon - `pushRaw()` expects `$payload` to be a json encoded string, but not base64 encoded. I will submit a pull request.

**Comment by ericgaonz** [comment]
@kainxspirits  Have you submitted the newest version to the Packagist?

**Comment by kainxspirits** [comment]
Not yet. I wanted to do that over the weekend but I was busy.
I will submit it tonight.
