### ISSUE TITLE
Job reservation is missing, unsuitable for scalability

### ISSUE THREAD

**Issue by v8-ict** [kainxspirits/laravel-pubsub-queue#23]
It looks live the driver does not honor job reservations like the redis or database driver.

At this point when you would run multiple instances of the queue worker, for example 10 workers. And PubSub having an acknowledge deadline of 10 seconds.
It is very likely that multiple workers run the same job.
(I was also able to actually reproduce this, multiple workers working on the same job ID)

An other flaw is the acknowledge deadline, if you have job that might take a couple of hours, it will probably exceed the PubSub acknowledge deadline;

Any thoughts how this is desired to be implemented?, i am happy to help out to write something for this.

I think building a reservation system like redis and the database driver would be an over complicated solution, while you cannot fetch a reserved job back, and delete it once it's released back to the queue, or should be deleted forever.

From my opinion it would be easier to: https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/modifyAckDeadline

The deadline should be synchronised, by the timeout setting of the queue worker if possible.

Assume that would solve both issues...

Let me know what u guys think

Thnx
Danny

**Comment by kainxspirits** [comment]
Hi @v8-ict 

I think a PR was submitted regarding this. You issue should be fixed if messages are acknowleged when received (in the current implementation, they are acknowleged after the proccessing).

I don't remember why I closed this PR, but feel free to submit a new one if you know how to fix it. Otherwise I will work on it when I have some free time.

**Comment by kainxspirits** [comment]
Fixed the acknowledgement issue on master branch. A new version will be pushed later this week with few other fixes.
