### ISSUE TITLE
No project ID was provided, and we were unable to detect a default project ID.

### ISSUE THREAD

**Issue by yunus89** [kainxspirits/laravel-pubsub-queue#33]
I did the following setup in Lumen 6 application

1. composer require kainxspirits/laravel-pubsub-queue

2. $app->register(Kainxspirits\PubSubQueue\PubSubQueueServiceProvider::class);

3. Added queue.php in config folder with the following content
----
  
     <?php

    use Illuminate\Support\Facades\File;

    return [
    'pubsub' => [
        'driver' => 'pubsub',
        'queue' => env('PUBSUB_QUEUE', 'iprocure'),
        'project_id' => env('PUBSUB_PROJECT_ID', 'iprocure-edw'),
        'retries' => 3,
        'request_timeout' => 60,
        'subscriber' => 'mytestsubscriber',
        'key_file' => File::get(storage_path('app/gcp-pubsub.json'))
    ]];

4. Added `$app->configure('queue');` in `bootstrap/app.php`

Then in my controller constructor i did the following

    use Kainxspirits\PubSubQueue\PubSubQueue;

    class ExampleController extends Controller
    {
         public function __construct(PubSubQueue $queue)
         {
             $this->queue = $queue;
         }

         public function testPubsub(){
        
         } 
     }

When i send request for `testPubsub()` i see the following error

    (1/1) GoogleException
    No project ID was provided, and we were unable to detect a default project ID.

**Comment by kainxspirits** [comment]
I've never used Lumen and that package was not tested for this framework. 

I don't know the difference between laravel and lumen, but I think your config file is wrong. The pubsub client should be inside a `connections` array. You can check the default queue config for reference : https://github.com/laravel/lumen-framework/blob/6.x/config/queue.php.

**Comment by yunus89** [comment]
I did change my `queue.php` file content to this, but it still fails

    <?php

    use Illuminate\Support\Facades\File;

    return [

    /*
    |--------------------------------------------------------------------------
    | Default Queue Connection Name
    |--------------------------------------------------------------------------
    |
    | Lumen's queue API supports an assortment of back-ends via a single
    | API, giving you convenient access to each back-end using the same
    | syntax for every one. Here you may define a default connection.
    |
    */

    'default' => env('QUEUE_CONNECTION', 'pubsub'),

    /*
    |--------------------------------------------------------------------------
    | Queue Connections
    |--------------------------------------------------------------------------
    |
    | Here you may configure the connection information for each server that
    | is used by your application. A default configuration has been added
    | for each back-end shipped with Lumen. You are free to add more.
    |
    | Drivers: "sync", "database", "beanstalkd", "sqs", "redis", "null"
    |
    */

    'connections' => [

        'pubsub' => [
            'driver' => 'pubsub',
            'queue' => env('PUBSUB_QUEUE', 'iprocure'),
            'project_id' => env('PUBSUB_PROJECT_ID', 'iprocure-edw'),
            'retries' => 3,
            'request_timeout' => 60,
            'subscriber' => 'mytestsubscriber',
            'key_file' => File::get(storage_path('app/gcp-pubsub.json'))
        ],

        'sync' => [
            'driver' => 'sync',
        ],

        'database' => [
            'driver' => 'database',
            'table' => env('QUEUE_TABLE', 'jobs'),
            'queue' => 'default',
            'retry_after' => 90,
        ],

        'beanstalkd' => [
            'driver' => 'beanstalkd',
            'host' => 'localhost',
            'queue' => 'default',
            'retry_after' => 90,
        ],

        'sqs' => [
            'driver' => 'sqs',
            'key' => env('SQS_KEY', 'your-public-key'),
            'secret' => env('SQS_SECRET', 'your-secret-key'),
            'prefix' => env('SQS_PREFIX', 'https://sqs.us-east-1.amazonaws.com/your-account-id'),
            'queue' => env('SQS_QUEUE', 'your-queue-name'),
            'region' => env('SQS_REGION', 'us-east-1'),
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => env('QUEUE_REDIS_CONNECTION', 'default'),
            'queue' => 'default',
            'retry_after' => 90,
            'block_for' => null,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Failed Queue Jobs
    |--------------------------------------------------------------------------
    |
    | These options configure the behavior of failed queue job logging so you
    | can control which database and table are used to store the jobs that
    | have failed. You may change them to any database / table you wish.
    |
    */

    'failed' => [
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => env('QUEUE_FAILED_TABLE', 'failed_jobs'),
    ],

     ];

**Comment by kainxspirits** [comment]
I tested it against the latest version of lumen (6.3.2) with pubsub emulator and it seems to work.

Also I'm not sure why you are trying to get the pubsub queue dependency from the constructor, that's not how it's supposed to work. Instead, you can use the classic _Laravel way_ to push a job into queue : 
* https://lumen.laravel.com/docs/6.x/queues
* https://laravel.com/docs/6.x/queues
