### ISSUE TITLE
Issue with multiple queues

### ISSUE THREAD

**Issue by ankurgoels** [kainxspirits/laravel-pubsub-queue#39]
Only a single subscription is created for all the topics which cause issues with multiple queues. 

The package subscribes topic to a subscription due to another queue(topic) is unable to subscribe to it.

A possible solution can be that we can create topics and subscription with that same name so they can be linked as I think Pubsub only support one topic per subscription. Please correct me if I am wrong anywhere.

**Comment by kainxspirits** [comment]
Hi,

I'm not sure what you are trying to achieve. If you have any sample codes that might help me to understand.

If you want another queue, you have to create another connection (I think it works the same way as the SQS official driver). That way you will be able to have another queue with another topic or subscription.
