### ISSUE TITLE
keyFile attribute doesn't work in Config array

### ISSUE THREAD

**Issue by Asif-Mahmood** [kainxspirits/laravel-pubsub-queue#68]
I am using this component in a project which is being deployed on the Google Cloud Run. For the pub/sub service account key, I am using google Secret manager rather than putting the JSON file in my codebase which would expose my secret. The Google Cloud pub/sub client library allows the actual JSON to be submitted after decoding it to an array. However, this fails in the current implementation on line 61 of Src/Connectors/PubSubConnector.php asit expects the $item to be string whereas in case of keyFile it is an Array. 
  If we pass the key.json content as json string without decoding, then it fails when this string is passed over to the Google Client Library where it expects it to be an array. Is anyone looking at this repo actively or I take a fork and create another composer for this. Please help & suggest.

**Comment by Asif-Mahmood** [comment]
![image](https://github.com/kainxspirits/laravel-pubsub-queue/assets/2041198/880c3f51-0a76-4208-826a-9acb0969f554)
Reference to the Google Client library.

**Comment by kainxspirits** [comment]
I'm not actively working on this package but if you send a PR I will look at it.
